use_frameworks!

target 'LottieButton_Example' do
    platform :ios, '8.0'

    pod 'LottieButton', :path => '../'
end

target 'LottieButton_Tests' do
    platform :ios, '8.0'

    pod 'LottieButton', :path => '../'

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
end

post_install do |installer|
    target = installer.pods_project.targets.find { |target| target.name == 'LottieButton' }
    debug_config = target.build_configurations.find { |config| config.name == 'Debug' }
    debug_config.build_settings['ENABLE_TESTABILITY'] = 'YES'
end
